import React, { useState, useEffect } from 'react';
import { listDebates } from '../services/api';
import { Link } from 'react-router-dom';

interface Debate {
  id: string;
  topic: string;
  status: string;
  created_at: string | null;
  completed_at: string | null;
  verdict: any;
}

const statusConfig: Record<string, { label: string; color: string; icon: string }> = {
  pending: { label: 'Pending', color: 'bg-gray-100 text-gray-700', icon: 'schedule' },
  running: { label: 'In Progress', color: 'bg-blue-100 text-blue-700', icon: 'update' },
  completed: { label: 'Completed', color: 'bg-green-100 text-green-700', icon: 'check_circle' },
  executed: { label: 'Executed', color: 'bg-purple-100 text-purple-700', icon: 'rocket_launch' },
  failed: { label: 'Failed', color: 'bg-red-100 text-red-700', icon: 'error' },
};

const HistoryPage: React.FC = () => {
  const [debates, setDebates] = useState<Debate[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<'all' | 'debate' | 'think'>('all');

  useEffect(() => { loadDebates(); }, []);

  const loadDebates = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await listDebates();
      setDebates(result.debates || []);
    } catch (err: any) {
      setError(err.message || 'Failed to load history');
    } finally {
      setLoading(false);
    }
  };

  const filtered = debates.filter(d =>
    d.topic.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-fade-in-up">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Session History</h1>
        <p className="text-sm text-gray-500 mt-1">Review, replay, and audit the collaborative intelligence sessions generated by your AI agents.</p>
      </div>

      {/* Toolbar */}
      <div className="flex items-center justify-between gap-4">
        <div className="relative flex-1 max-w-md">
          <span className="material-icons absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-lg">search</span>
          <input
            type="text"
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search sessions..."
            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
        <div className="flex items-center gap-2">
          {(['all', 'debate', 'think'] as const).map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                filter === f ? 'bg-gray-900 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              {f === 'all' ? 'All' : f === 'debate' ? 'Debates' : 'Think'}
            </button>
          ))}
        </div>
      </div>

      {/* Loading */}
      {loading && (
        <div className="flex items-center justify-center py-12">
          <svg className="animate-spin h-6 w-6 text-blue-500" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          <span className="ml-3 text-sm text-gray-500">Loading sessions...</span>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="text-center py-8">
          <span className="material-icons text-red-400 text-4xl mb-2">error</span>
          <p className="text-sm text-red-600 mb-4">{error}</p>
          <button onClick={loadDebates} className="px-4 py-2 bg-blue-500 text-white rounded-lg text-sm hover:bg-blue-600">Retry</button>
        </div>
      )}

      {/* Empty State */}
      {!loading && !error && filtered.length === 0 && (
        <div className="text-center py-16">
          <span className="material-icons text-gray-300 text-5xl mb-4">inbox</span>
          <h3 className="text-lg font-medium text-gray-900 mb-1">No sessions yet</h3>
          <p className="text-sm text-gray-500 mb-4">Start your first debate or thinking session</p>
          <Link to="/" className="inline-flex items-center gap-1.5 px-4 py-2 bg-blue-500 text-white rounded-lg text-sm font-medium hover:bg-blue-600">
            <span className="material-icons text-base">add</span>
            Get Started
          </Link>
        </div>
      )}

      {/* Session Cards */}
      {!loading && filtered.length > 0 && (
        <div className="space-y-3">
          {filtered.map((debate, index) => {
            const cfg = statusConfig[debate.status] || statusConfig.pending;
            return (
              <Link
                key={debate.id}
                to={`/debate/${debate.id}`}
                className="block bg-white rounded-xl p-5 border border-gray-100 shadow-sm hover:shadow-md transition-all"
                style={{ animationDelay: `${index * 50}ms` }}
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="material-icons text-blue-500 text-base">forum</span>
                      <h3 className="text-base font-semibold text-gray-900 truncate">{debate.topic}</h3>
                    </div>
                    <div className="flex items-center gap-3 text-xs text-gray-500">
                      <span>Multi-Agent Debate</span>
                      <span>•</span>
                      <span>{debate.created_at ? new Date(debate.created_at).toLocaleString() : ''}</span>
                    </div>
                    {debate.verdict && (
                      <p className="text-sm text-gray-600 mt-2 line-clamp-2">
                        {debate.verdict.recommendation?.substring(0, 120)}...
                      </p>
                    )}
                  </div>
                  <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${cfg.color} flex-shrink-0`}>
                    <span className="material-icons text-sm">{cfg.icon}</span>
                    {cfg.label}
                  </span>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default HistoryPage;
